default: &default
  adapter: <%= ENV['database_adapter'] %> 
  encoding: utf8
  username: <%= ENV['database_user'] %>
  password: <%= ENV['database_password'] %>
  host: <%= ENV['database_address'] %>
  port: 3306

development:
  <<: *default
  database: dev_tpi_ruby

# test:
#   <<: *default
#   database: test_tpi_ruby

production:
  <<: *default
  database: tpi_ruby
