default: &default
  adapter: mysql2
  encoding: utf8
  username: <%= ENV['database_user'] %>
  password: <%= ENV['database_password'] %>
  host: 192.168.0.162
  port: 3306

development:
  <<: *default
  database: dev_tpi_ruby

# test:
#   <<: *default
#   database: test_tpi_ruby

production:
  <<: *default
  database: tpi_ruby
